"""make subject_common_name nullable in invitation

Revision ID: 9cd3491e245b
Revises: eb8fc5b2ae47
Create Date: 2026-05-13 23:50:10.755018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9cd3491e245b'
down_revision: Union[str, Sequence[str], None] = 'eb8fc5b2ae47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tinyinvitation', 'subject_common_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tinyinvitation', 'subject_common_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
