"""initial migration

Revision ID: eb8fc5b2ae47
Revises: 
Create Date: 2026-05-13 14:25:58.957592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb8fc5b2ae47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acmeaccount',
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('acmecert',
    sa.Column('object_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('tinyjwkprovisioner',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provisioner_jwe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provisioner_jwe_kid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('tinysystemmetadata',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('x509certificate',
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('subject_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_alt_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('key_usage', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ext_key_usage', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('issuer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fingerprint_sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('time_not_before', sa.DateTime(), nullable=False),
    sa.Column('time_not_after', sa.DateTime(), nullable=False),
    sa.Column('cert_pem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('serial_no'),
    sa.UniqueConstraint('cert_pem'),
    sa.UniqueConstraint('fingerprint_sha256')
    )
    op.create_index(op.f('ix_x509certificate_ext_key_usage'), 'x509certificate', ['ext_key_usage'], unique=False)
    op.create_index(op.f('ix_x509certificate_issuer_name'), 'x509certificate', ['issuer_name'], unique=False)
    op.create_index(op.f('ix_x509certificate_key_usage'), 'x509certificate', ['key_usage'], unique=False)
    op.create_index(op.f('ix_x509certificate_subject_alt_names'), 'x509certificate', ['subject_alt_names'], unique=False)
    op.create_index(op.f('ix_x509certificate_subject_name'), 'x509certificate', ['subject_name'], unique=False)
    op.create_index(op.f('ix_x509certificate_time_not_after'), 'x509certificate', ['time_not_after'], unique=False)
    op.create_index(op.f('ix_x509certificate_time_not_before'), 'x509certificate', ['time_not_before'], unique=False)
    op.create_table('x509certificatedata',
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('provisioner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provisioner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provisioner_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_issuance_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('serial_no')
    )
    op.create_index(op.f('ix_x509certificatedata_provisioner_id'), 'x509certificatedata', ['provisioner_id'], unique=False)
    op.create_index(op.f('ix_x509certificatedata_provisioner_name'), 'x509certificatedata', ['provisioner_name'], unique=False)
    op.create_table('x509certificaterevocation',
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.Column('provisioner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason_code', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('token_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mtls', sa.Boolean(), nullable=False),
    sa.Column('acme', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('serial_no')
    )
    op.create_index(op.f('ix_x509certificaterevocation_acme'), 'x509certificaterevocation', ['acme'], unique=False)
    op.create_index(op.f('ix_x509certificaterevocation_expires_at'), 'x509certificaterevocation', ['expires_at'], unique=False)
    op.create_index(op.f('ix_x509certificaterevocation_mtls'), 'x509certificaterevocation', ['mtls'], unique=False)
    op.create_index(op.f('ix_x509certificaterevocation_provisioner_id'), 'x509certificaterevocation', ['provisioner_id'], unique=False)
    op.create_index(op.f('ix_x509certificaterevocation_reason'), 'x509certificaterevocation', ['reason'], unique=False)
    op.create_index(op.f('ix_x509certificaterevocation_reason_code'), 'x509certificaterevocation', ['reason_code'], unique=False)
    op.create_index(op.f('ix_x509certificaterevocation_revoked_at'), 'x509certificaterevocation', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_x509certificaterevocation_token_id'), 'x509certificaterevocation', ['token_id'], unique=False)
    op.create_table('tinyblueprint',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provisioner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('not_before', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('not_after_days', sa.Integer(), nullable=False),
    sa.Column('invitation_validity_days', sa.Integer(), nullable=False),
    sa.Column('key_algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('keygen_flow', sa.Enum('CLIENT_SIDE', 'SERVER_SIDE', name='keygenflow'), nullable=False),
    sa.Column('subject_mode', sa.Enum('DEFAULT', 'SIMPLE_DNS', 'SIMPLE_EMAIL', name='subjectmode'), nullable=False),
    sa.ForeignKeyConstraint(['provisioner_name'], ['tinyjwkprovisioner.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_tinyblueprint_provisioner_name'), 'tinyblueprint', ['provisioner_name'], unique=False)
    op.create_table('tinyinvitation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submit_nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redeem_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blueprint_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_common_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_alt_names', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('template_data', sa.JSON(), nullable=True),
    sa.Column('not_after_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'OPENED', 'LOCKED', 'EXCEPTION', 'ISSUED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('serial_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keygen_flow', sa.Enum('CLIENT_SIDE', 'SERVER_SIDE', name='keygenflow'), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_name'], ['tinyblueprint.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redeem_code_hash'),
    sa.UniqueConstraint('serial_no'),
    sa.UniqueConstraint('submit_nonce')
    )
    op.create_index(op.f('ix_tinyinvitation_blueprint_name'), 'tinyinvitation', ['blueprint_name'], unique=False)
    op.create_index(op.f('ix_tinyinvitation_subject_alt_names'), 'tinyinvitation', ['subject_alt_names'], unique=False)
    op.create_index(op.f('ix_tinyinvitation_subject_common_name'), 'tinyinvitation', ['subject_common_name'], unique=False)
    # ### end Alembic commands ###
    op.execute(
        sa.text("INSERT INTO tinysystemmetadata (key, value) VALUES ('sync_state', '{}')")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tinyinvitation_subject_common_name'), table_name='tinyinvitation')
    op.drop_index(op.f('ix_tinyinvitation_subject_alt_names'), table_name='tinyinvitation')
    op.drop_index(op.f('ix_tinyinvitation_blueprint_name'), table_name='tinyinvitation')
    op.drop_table('tinyinvitation')
    op.drop_index(op.f('ix_tinyblueprint_provisioner_name'), table_name='tinyblueprint')
    op.drop_table('tinyblueprint')
    op.drop_index(op.f('ix_x509certificaterevocation_token_id'), table_name='x509certificaterevocation')
    op.drop_index(op.f('ix_x509certificaterevocation_revoked_at'), table_name='x509certificaterevocation')
    op.drop_index(op.f('ix_x509certificaterevocation_reason_code'), table_name='x509certificaterevocation')
    op.drop_index(op.f('ix_x509certificaterevocation_reason'), table_name='x509certificaterevocation')
    op.drop_index(op.f('ix_x509certificaterevocation_provisioner_id'), table_name='x509certificaterevocation')
    op.drop_index(op.f('ix_x509certificaterevocation_mtls'), table_name='x509certificaterevocation')
    op.drop_index(op.f('ix_x509certificaterevocation_expires_at'), table_name='x509certificaterevocation')
    op.drop_index(op.f('ix_x509certificaterevocation_acme'), table_name='x509certificaterevocation')
    op.drop_table('x509certificaterevocation')
    op.drop_index(op.f('ix_x509certificatedata_provisioner_name'), table_name='x509certificatedata')
    op.drop_index(op.f('ix_x509certificatedata_provisioner_id'), table_name='x509certificatedata')
    op.drop_table('x509certificatedata')
    op.drop_index(op.f('ix_x509certificate_time_not_before'), table_name='x509certificate')
    op.drop_index(op.f('ix_x509certificate_time_not_after'), table_name='x509certificate')
    op.drop_index(op.f('ix_x509certificate_subject_name'), table_name='x509certificate')
    op.drop_index(op.f('ix_x509certificate_subject_alt_names'), table_name='x509certificate')
    op.drop_index(op.f('ix_x509certificate_key_usage'), table_name='x509certificate')
    op.drop_index(op.f('ix_x509certificate_issuer_name'), table_name='x509certificate')
    op.drop_index(op.f('ix_x509certificate_ext_key_usage'), table_name='x509certificate')
    op.drop_table('x509certificate')
    op.drop_table('tinysystemmetadata')
    op.drop_table('tinyjwkprovisioner')
    op.drop_table('acmecert')
    op.drop_table('acmeaccount')
    # ### end Alembic commands ###
