FROM python:3.14.3-alpine3.23
RUN apk add build-base libpq libpq-dev
ENV PYTHONUNBUFFERED=1

WORKDIR /app
RUN mkdir -p /app/webapp
COPY ./webapp/pyproject.toml /app/webapp/pyproject.toml

RUN pip install /app/webapp
COPY ./ /app

CMD [ "python", "-u", "-m", "app.indexer" ]
