FROM python:3.14.3-alpine3.23
RUN apk add build-base libpq libpq-dev
WORKDIR /
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY ./ /app
CMD ["python", "-u", "-m", "app.indexer"]
