FROM python:3.14.3-alpine3.23
RUN apk add build-base libpq libpq-dev
ENV PYTHONUNBUFFERED=1

WORKDIR /webapp
COPY ./pyproject.toml /webapp/pyproject.toml

RUN pip install /webapp
COPY ./ /webapp

CMD [ "/webapp/entrypoint.sh" ]
